### PR TITLE
Add Scalastyle lint config

### PR DESCRIPTION
**Pull request by keynmol**
A config for [Scalastyle linter](http://www.scalastyle.org/configuration.html)

### CODE REVIEW

**Comment by Lugrin** [comment]
Did you add all possible checkers? (http://www.scalastyle.org/rules-0.8.0.html)

**Comment by jsgriffin** [comment]
Cor that XML. Who would ever choose to work with a language like this.

**Comment by dav009** [comment]
`PublicMethodsHaveTypeChecker` so all our methods should be like `def a():Something`?

**Comment by dav009** [comment]
besides the previous rule, I think all the other ones look sensible to me

**Comment by Lugrin** [comment]
@dav009 only the public ones. http://www.scalastyle.org/rules-0.8.0.html#org_scalastyle_scalariform_PublicMethodsHaveTypeChecker

**Comment by dav009** [comment]
well, looks alright, I think so far I just dislike the mentioned rule.

**Comment by keynmol** [comment]
The mentioned rule is actually a very good one. Public methods should have a return type so you can infer what they return without having an IDE.

**Pull request merged**
